tianocore/edk2-test

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/ConfigKeywordHandler/BlackBoxTest/Dependency/SampleDriver/DriverSample.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/ConfigKeywordHandler/BlackBoxTest/Dependency/SampleDriver/DriverSampleDxe.inf

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2145
Replace the gEfiFormBrowserExProtocolGuid with gEdkiiFormBrowserExProtocolGuid, remove the unnecessary declaration.
Signed-off-by: Irene Park <ipark@nvidia.com>

uefi-sct/SctPkg: Remove gEfiFormBrowserExProtocolGuid

---

uefi-sct/HowToBuild/How to build SCT.txt
uefi-sct/SctPkg/UEFI/IHV_SCT.dsc
uefi-sct/SctPkg/UEFI/UEFI_SCT.dsc
uefi-sct/SctPkg/build.sh

Update the SctPkg build scripts and HowTo to build for AARCH64
with latest EDK2, without depending on UDK2017.
This series depends on the change in:
https://edk2.groups.io/g/devel/message/60407
Samer El-Haj-Mahmoud (3):
uefi-sct/SctPkg: Fix build with latest EDK2
uefi-sct/SctPkg: Add build instructions with latest EDK2
uefi-sct/SctPkg: Remove obsolete version macros

Build Aarch64 with latest EDK2 

---

uefi-sct/HowToBuild/How to build SCT.txt
uefi-sct/SctPkg/TestCase/RIVL/Protocol/SimpleNetwork/SimpleNetworkENTSTestCase.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/MiscBootServices/BlackBoxTest/MiscBootServicesBBTestFunction.c
uefi-sct/SctPkg/TestCase/UEFI/IHV/Protocol/DriverBinding/BlackBoxTest/DriverBindingBBTestFunction.c
uefi-sct/SctPkg/TestInfrastructure/SCT/Drivers/StandardTest/StandardTest.c
uefi-sct/SctPkg/TestInfrastructure/SCT/Framework/ENTS/EasDispatcher/Core/Eas.c
uefi-sct/SctPkg/TestInfrastructure/SCT/Framework/ENTS/EasDispatcher/Exec/EasCmdDisp.c
uefi-sct/SctPkg/UEFI/IHV_SCT.dsc
uefi-sct/SctPkg/UEFI/UEFI_SCT.dsc
uefi-sct/SctPkg/build.sh

Not all platforms implement GetTime(), but the SCT just assumes calls to
GetTime will be successful. If GetTime() doesn't return EFI_SUCCESS,
then the EFI_TIME value will be uninitialized data.
Fix by checking the GetTime() return code. If it doesn't return
EFI_SUCCESS, then use the traditional 1/1/1970 epoch so that the test
report at least looks sane, but it is obvious that we don't have a valid
timestamp.
https://edk2.groups.io/g/devel/message/63588

[PATCH] Check return status on calls to GetTime()

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/RuntimeServices/VariableServices/BlackBoxTest/AuthVariableServicesBBTestConformance.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2865
QueryVariableInfo() returning EFI_SUCCESS for a legal combination of attributes is not an error.

uefi-sct/SctPkg: fix variable services conformance test

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/RandomNumber/BlackBoxTest/RandomNumberBBTestConformance.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2438
The EFI_RNG_PROTOCOL conformance test checks that the size returned by
GetInfo() is a multiple of 16. This would be fulfilled by size == 0.
The UEFI specification requires that at least one algorithm is implemented.
So we should check that size is non-zero too.

uefi-sct/SctPkg: EFI_RNG_PROTOCOL.GetInfo check size != 0

---

uefi-sct/SctPkg/build.sh

gcc_version returned by compiler is a string, and needs to be converted to a integer before testing
Cc: Irene Park <ipark@nvidia.com>
Cc: Heinrich Schuchardt <xypron.glpk@gmx.de>
Signed-off-by: Joseph Hemann <joseph.hemann@arm.com>
Change-Id: I24f3f52c12660928b58e6f836fdef86890688d26

uefi-sct/SctPkg: Changed gcc version to be integer

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/RuntimeServices/TimeServices/BlackBoxTest/TimeServicesBBTestFunction.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2407
%s/Verity/Verify/g

uefi-sct/SctPkg: typo Verity in TimeServicesBBTestFunction

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/MemoryAllocationServices/BlackBoxTest/MemoryAllocationServicesBBTestFunction.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2671
AllocatePages Functionality test.
Existing Code Increase Start address by 64k, even if Start is already aligned to 64k.
Suggested Change will not modify Start,
if Start is already aligned to 64k
For Eg.
Available Memory(Start is aligned to 64k):
Start      End      PageNum(Free Pages)
80000000  EBD6EFFF  6BD6F(Number of Free pages are not 64k Aligned)
edk2-test code:
Start is increased & aligned by 64k(Equal to 16 pages of size 4k each).
Request for Pagenum is minus by 16 Pages.
Start = (Start + 0x10000) & 0xFFFFFFFFFFFF0000 Start = (0x80000000 + 0x10000) & 0xFFFFFFFFFFFF0000 = 0x80010000 PageNum = PageNum - EFI_SIZE_TO_PAGES(0x10000) = 0x6BD6F - 0x10 = 0x6BD5F
edk2 memory allocation code to Align the requested pages to 64k …

SctPkg: Updated Start Address Alignment code

---

uefi-sct/Maintainers.txt

Request to add Barton Gao from Byosoft as maintainer of uefi-sct.
Signed-off-by: Barton Gao <gaojie@byosoft.com.cn>

uefi-sct:Add maintainer in Maintainers.txt

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/ConfigKeywordHandler/BlackBoxTest/Dependency/SampleDriver/DriverSample.c

EDK2 has removed some deprecated function wrappers. The BlackBoxTest
still uses StrnCpy() and UnicodeValueToString(). This patch fixes the
build by moving to UnicodeValueToStringS(). However, the code using
StrnCpy() is simply #ifdef'd out because on reading the code it is
apparent that the testcase is non-functional and the fix is not
straightforward. As I understand it, there are no functional
implementations of the interface in the wild anyway. If/when it does
become important someone can do the work of making a proper test case.
Fixes: Bug 2068
Signed-off-by: Grant Likely <grant.likely@...>
Cc: Samer El-Haj-Mahmoud <Samer.El-Haj-Mahmoud@...>
Cc: G Edhaya Chandran <@edhay>
Cc: Eric Jin <eric.jin@...>
Cc: Barton Gao <gaojie@...>
Reviewed-by: Samer El-Haj-Mahmoud …

Fix missing symbols on edk2-test build

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Generic/EfiCompliant/BlackBoxTest/EfiCompliantBBTestPlatform_uefi.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3065
If LocateProtocol() has failed, variable Ebc is not valid and we may not dereference it.
Reviewed-by: Grant Likely <grant.likely@arm.com>

uefi-sct/SctPkg: illegal dereference in CheckEbcProtocol()

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/DevicePathToText/BlackBoxTest/DevicePathToTextBBTestCoverage.c

Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=3029
Function DevicePathToTextConvertDeviceNodeToTextCoverageTest() tests if
DeviceNodeToText() correctly converts a Relative Offset Range node. After calling SctConvertTextToDeviceNode() it tries to set the field Reserved of the returned device node to 0.
If the tested firmware does not return the expected text
SctConvertTextToDeviceNode() may return NULL or a device node that is shorter than expected. In both cases it is not possible to access the field Reserved.
So we must check both that the returned node is not NULL and that it has the exepected size.
Due to the missing check a NULL dereference was observed when running the SCT on U-Boot.
Reviewed-by: G Edhaya …

uefi-sct/SctPkg: NULL deref in DevicePathToText test

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/UnicodeCollation/BlackBoxTest/UnicodeCollationBBTestFunction.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/UnicodeCollation2/BlackBoxTest/UnicodeCollation2BBTestFunction.c

On systems with memory protection enabled the modification of local function initialization data results in permission issue. Make a copy of data prior to modification.
Signed-off-by: Jeff Brasen <jbrasen@nvidia.com>
Reviewed-By: Samer El-Haj-Mahmoud <Samer.El-Haj-Mahmoud@arm.com>

uefi-sct/SctPkg: Correct issue with memory protection enabled.

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/DevicePathToText/BlackBoxTest/DevicePathToTextBBTestCoverage.c

Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=3029
After commit 75c92b85bf9b ("uefi-sct/SctPkg: NULL deref in DevicePathToText
test") a build failure was observed.
Length is a field in MEDIA_OFFSET_DEVICE_PATH.Header and not in MEDIA_OFFSET_DEVICE_PATH itself.
Fixes: 75c92b85bf9b ("uefi-sct/SctPkg: NULL deref in DevicePathToText test")

uefi-sct/SctPkg: build failure DevicePathToText test

---

uefi-sct/SctPkg/build.sh

The build.sh script is very useful for setting up the build environment
before calling the package build. Sometimes additional packages are
needed when building the SCT. (e.g., it is useful to build ShellPkg).
Refactor the build code to allow additional DSCs to be added to the
build.
This patch is useful when building a full SCT image that includes the
EDK2 shell.
Signed-off-by: Grant Likely <grant.likely@arm.com>

edk2-test: Add support for building extra packages

---

uefi-sct/SctPkg/build.sh

gcc compilers versions 5.* also need to be converted from string to integer before testing
Cc: Irene Park <ipark@nvidia.com>
Cc: Heinrich Schuchardt <xypron.glpk@gmx.de>
Cc: Stuart Yoder <Stuart.Yoder@arm.com>
Signed-off-by: Joseph Hemann <Joseph.heman@arm.com>
Reviewed-by: Heinrich Schuchardt <xypron.glpk@gmx.de>
Reviewed-By: G Edhaya Chandran <edhaya.chandran@arm.com>

uefi-sct/SctPkg: Changed compiler check from greater 5 to equal to 5

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestConformance_efi.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestConformance_uefi.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestFunction_efi.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestFunction_uefi.c
uefi-sct/SctPkg/TestCase/UEFI/IHV/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestConformance_uefi.c
uefi-sct/SctPkg/TestCase/UEFI/IHV/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestFunction_uefi.c
uefi-sct/SctPkg/TestInfrastructure/SCT/Framework/UI/KeyFunction.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3244

[Bug3244] uefi-sct/SctPkg: typo Positoin

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestFunction_uefi.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3253
SctPrint() requires that %d refers to an UINTN parameter.
SimpleTextOutBBTestFunction_uefi.c has a lot of
StandardLib->RecordAssertion() calls where an INT32 is passed
as argument for a '%d' print code.
This leads to incorrect output like:
MaxMode=-549755813885,
-549755813885 is 0x0xFFFFFF8000000003. So MaxMode actually
is an INT32 with value 3 in this example.
Convert the parameters to UINTN.

[Bug 3253] uefi-sct/SctPkg: type mismatch in SimpleTextOut test

---

uefi-sct/SctPkg/buildzip.sh

CapsuleApp.efi is necessary for testing capsule updates of the firmware.
Add it into the default build.
Signed-off-by: Grant Likely <grant.likely@arm.com>

buildzip: Add CapsuleApp.efi to the SCT zip file

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/FirmwareManagement/BlackBoxTest/FirmwareManagementBBTestConformance.c
uefi-sct/SctPkg/TestCase/UEFI/IHV/Protocol/FirmwareManagement/BlackBoxTest/FirmwareManagementBBTestConformance.c

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3272
The goal of the Support Routine: CheckForSupportGetImage is to detect the
current FMP instance's capability for supporting GetImage().
In current code, "ImageIndex = 0" is the input parameter, but it is
inconsistent with spec -"A unique number identifying the firmware image(s)
within the device. The number is between 1 and DescriptorCount."
It is a bug and need the fix.
The similar errors exist in CheckForSupportSetImage/CheckForSupportCheckImage.
Signed-off-by: Eric Jin <eric.jin@intel.com>
Reviewed-by: Barton Gao <gaojie@byosoft.com.cn>
Reviewed-by: G …

ImageIndex need be corrected to range 1 ~ DescriptorCount.

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleNetwork/BlackBoxTest/SimpleNetworkBBTestFunction.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3257
SctPrint() requires that %x and %d refers to an UINTN parameter.
SimpleNetworkBBTestFunction.c tries to print INT32 using %x, %d without converting to UINTN resulting in corrupted output like:
SimpleNetworkBBTestFunction.c:891:
Status - Unsupported, Filter - AAAA00000000
Mode->ReceiveFilterSetting has only 32 bit. The true value is 0.
Convert the parameters to UINTN.

uefi-sct/SctPkg: type mismatch in Simple Network test

---

uefi-sct/SctPkg/TestCase/UEFI/IHV/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestFunction_uefi.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3253
SctPrint() requires that %d refers to an UINTN parameter.
SimpleTextOutBBTestFunction_uefi.c has a lot of
StandardLib->RecordAssertion() calls where an INT32 is passed
as argument for a '%d' print code.
This leads to incorrect output like:
MaxMode=-549755813885,
-549755813885 is 0x0xFFFFFF8000000003. So MaxMode actually
is an INT32 with value 3 in this example.
Convert the parameters to UINTN.

uefi-sct/SctPkg: IHV: type mismatch in SimpleTextOut test

---

uefi-sct/SctPkg/TestCase/UEFI/IHV/Protocol/SimpleNetwork/BlackBoxTest/SimpleNetworkBBTestFunction.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3257
SctPrint() requires that %x and %d refers to an UINTN parameter.
SimpleNetworkBBTestFunction.c tries to print INT32 using %x, %d without
converting to UINTN resulting in corrupted output like:
SimpleNetworkBBTestFunction.c:891:
Status - Unsupported, Filter - AAAA00000000
Mode->ReceiveFilterSetting has only 32 bit. The true value is 0.
Convert the parameters to UINTN.

uefi-sct/SctPkg: IHV: type mismatch in Simple Network test

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/EventTimerTaskPriorityServices/BlackBoxTest/EventTimerTaskPriorityServicesBBTestCreateEvent.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/EventTimerTaskPriorityServices/BlackBoxTest/EventTimerTaskPriorityServicesBBTestCreateEventEx.c

The commits a9d1fb58 and ae7e5477b555 caused SCT BS.CreateEvent failures.
Section 7.1 of the UEFI Spec states that TPL_HIGH_LEVEL is designed for
exclusive use by the firmware. The creation of events by UEFI
applications, UEFI drivers, and UEFI OS Loaders should not use this TPL
level.
Therefore, revert TPL_HIGH_LEVEL change in commits a9d1fb58 and
ae7e5477b555 to not create event with TPL_HIGH_LEVEL to be compliant
with UEFI Spec and fix the failures.
For more information, https://edk2.groups.io/g/devel/message/76338
Cc: Heinrich Schuchardt <xypron.glpk@gmx.de>
Cc: Michael D Kinney <michael.d.kinney@intel.com>
Signed-off-by: Sunny Wang …

uefi-sct/SctPkg: Not create event with TPL_HIGH_LEVEL

---

uefi-sct/SctPkg/UEFI/IHV_SCT.dsc
uefi-sct/SctPkg/UEFI/UEFI_SCT.dsc

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3246
MdeLibs.dsc.inc was added for some basic/default library
instances provided by MdePkg, RegisterFilterLibNull which will be
consumed by IoLib and BaseLib was added in MdeLibs.dsc.inc.
To build UefiSct with edk2-stable202105 and later, this file
must be included in dsc file.
Signed-off-by: Barton Gao <gaojie@byosoft.com.cn>

SctPkg: Consume MdeLibs.dsc.inc for RegisterFilterLib

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/MemoryAllocationServices/BlackBoxTest/MemoryAllocationServicesBBTestFunction.c

This is to fix the SCT BS.AllocatePages failures (not found) with the case that the Start address is not aligned to 64k.
For example,
The following is available memory region for testing:
0000000082012000-00000000EB6D9FFF 00000000000696C8
With the current page alignment calculation, we will get:
Start address is 0x82020000
PageNum is 0x696B8
In BS.AllocatePages, it will make the end address align with 64k,
so PageNum will be changed from 0x696B8 to 0x696C0. Therefore, the
end address will become 0xEB6E0000 which is larger than 0xEB6D9FFF,
so we get not found error in the end.
Therefore, the calculation for getting the PageNum should be updated to PageNum - (2 * EFI_SIZE_TO_PAGES(0x10000)) so that we won't get a wrong PageNum to allocate a memory with a size larger than available space's …

uefi-sct/SctPkg: Update page alignment calculations

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/RuntimeServices/VariableServices/BlackBoxTest/VariableServicesBBTestConformance.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3469
The Self Certification Test (SCT) II Case Specification, 2017 requires
in 5.2.1.4.5. that QueryVariableInfo() shall fail for
attributes = EFI_VARIABLE_NON_VOLATILE.
Add EFI_VARIABLE_NON_VOLATILE to tested values in function
QueryVariableInfoConfTestSub5().

uefi-sct/SctPkg: uefi-sct:QueryVariableInfo(EFI_VARIABLE_NON_VOLATILE)

---

uefi-sct/SctPkg/SCRT/SCRTDriver/Aarch64/Dump.c
uefi-sct/SctPkg/SCRT/SCRTDriver/Arm/Dump.c
uefi-sct/SctPkg/SCRT/SCRTDriver/Riscv64/Dump.c

SctAPrint uses boot services functions but is called after ExitBootServices. Replace with call to Printf which is safe for use in runtime.
Signed-off-by: Jeff Brasen <jbrasen@nvidia.com>

SctPkg: Fix runtime access to boot services functions

---

uefi-sct/Maintainers.txt

This patch proposes Carolyn Gjertsen as maintainer of edk2-test
repository and Supreeth Venkatesh as reviewer from AMD.
Signed-off-by: Supreeth Venkatesh <supreeth.venkatesh@amd.com>
Reviewed-By: Samer El-Haj-Mahmoud <Samer.El-Haj-Mahmoud@arm.com>

uefi-sct: Propose maintainers from AMD

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/MemoryAllocationServices/BlackBoxTest/MemoryAllocationServicesBBTestFunction.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2284
EFI_MEMORY_TYPE is an enum. SctPrint expects an UINTN when printing with %d. Add missing conversions in MemoryAllocationServicesBBTestFunction.

uefi-sct/SctPkg: correct print code for EFI_MEMORY_TYPE

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/RuntimeServices/TimeServices/BlackBoxTest/TimeServicesBBTestConformance.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2529
According to the UEFI specification EFI_TIME.YEAR may take values in the
range 1900-9999. The specification does not forbid to set a wakeup time in
the past. We should not expect EFI_INVALID_PARAMETER to be returned by
SetWakeupTime() for the years 1997 and 2100.
Values 1899 and 10000 must lead to this error code.
Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>

uefi-sct/SctPkg: invalid values for SetWakeupTime()

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/PxeBaseCode/BlackBoxTest/PxeBaseCodeBBTestFunction.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleNetwork/BlackBoxTest/SimpleNetworkBBTestConformance.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleNetwork/BlackBoxTest/SimpleNetworkBBTestFunction.c
uefi-sct/SctPkg/TestCase/UEFI/IHV/Protocol/PxeBaseCode/BlackBoxTest/PxeBaseCodeBBTestFunction.c
uefi-sct/SctPkg/TestCase/UEFI/IHV/Protocol/SimpleNetwork/BlackBoxTest/SimpleNetworkBBTestConformance.c
uefi-sct/SctPkg/TestCase/UEFI/IHV/Protocol/SimpleNetwork/BlackBoxTest/SimpleNetworkBBTestFunction.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3145
The SimpleNetwork protocol related test cases don't allow some
functions to return EFI_UNSUPPORTED, which doesn't comply with UEFI
spec.
UEFI spec allows EFI_SIMPLE_TEXT_OUT_PROTOCOL functions below to
return EFI_UNSUPPORTED.
- ReceiveFilters()
- Statistics()
- NvData()
- StationAddress()
- Reset()
Therefore, update the test cases that consume the functions above
to fix this issue.
Cc: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>
Signed-off-by: Sunny Wang <sunny.wang@arm.com>

uefi-sct/SctPkg: Allow some SNP functions to return EFI_UNSUPPORTED

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestConformance_efi.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestConformance_uefi.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestFunction_efi.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestFunction_uefi.c
uefi-sct/SctPkg/TestCase/UEFI/IHV/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestConformance_uefi.c
uefi-sct/SctPkg/TestCase/UEFI/IHV/Protocol/SimpleTextOut/BlackBoxTest/SimpleTextOutBBTestFunction_uefi.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3738
The SimpleTestOut test cases don't allow SetMode to return
EFI_UNSUPPORTED, which doesn't comply with UEFI spec.
UEFI spec allows EFI_SIMPLE_TEXT_OUT_PROTOCOL.SetMode function to
return EFI_UNSUPPORTED for the condition below:
if the output devices support 80x50, that is defined to be mode 1.
All other text dimensions supported by the device will follow as
modes 2 and above. If an output device supports modes 2 and above,
but does not support 80x50, then querying for mode 1 will return
EFI_UNSUPPORTED.
Therefore, update the test cases to fix this issue.
Cc: Heinrich Schuchardt …

uefi-sct/SctPkg: Allow SimpleTextOut SetMode to return EFI_UNSUPPORTED

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/MiscBootServices/BlackBoxTest/MiscBootServicesBBTestFunction.c

Updated the check for montonic count in the case of after restart
From the UEFI Spec:
"The platform?s monotonic counter is comprised of two parts: the high 32 bits and the low 32 bits.
The low 32-bit value is volatile and is reset to zero on every system reset.
It is increased by 1 on every call to GetNextMonotonicCount().
The high 32-bit value is nonvolatile and is increased by one on
whenever the system resets or the low 32-bit counter overflows."
It was found in one case where the higher 32-bit increased by 2
presumably due to the overflow of lower 32-bit counter.
Update the logic to handle this case and to print a warning.
Please find more details in the ticket: https://bugzilla.tianocore.org/show_bug.cgi?id=2774
Cc: Carolyn Gjertsen …

UEFI-SCT: SctPkg: Updated the check for monotonic count after restart

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/MiscBootServices/BlackBoxTest/MiscBootServicesBBTestFunction.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/MiscBootServices/BlackBoxTest/MiscBootServicesBBTestMain.h

The Stall_Func test on the highest TPL causes issues with the disk IO by blocking interrupts. This blocking can cause disk corruption through IO timeouts. Since this doesn't seem to be the intent of the test this revision reduces the stall interval from 10 seconds to 4 and adjusts the delta tolerance in scale.
Signed-off-by: Robert Wood <rwood.ce@comcast.net>

MiscBootServices: Stall_Func: Reduces the stall interval for Stall_Func

---

uefi-sct/SctPkg/Application/InstallSct/InstallSctDef.h
uefi-sct/SctPkg/Library/SctLib/LoongArch64/SctLibPlat.h
uefi-sct/SctPkg/Library/SctLib/LoongArch64/initplat.c
uefi-sct/SctPkg/Library/SctLib/SctLib.inf
uefi-sct/SctPkg/SCRT/SCRTApp/LoongArch64/GoVirtual.S
uefi-sct/SctPkg/SCRT/SCRTApp/LoongArch64/VirtualMemory.c
uefi-sct/SctPkg/SCRT/SCRTApp/SCRTApp.inf
uefi-sct/SctPkg/SCRT/SCRTDriver/LoongArch64/Debug.c
uefi-sct/SctPkg/SCRT/SCRTDriver/LoongArch64/Dump.c
uefi-sct/SctPkg/SCRT/SCRTDriver/LoongArch64/Io.c
uefi-sct/SctPkg/SCRT/SCRTDriver/SCRTDriver.inf
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/DebugSupport/BlackBoxTest/DebugSupportBBTest.inf
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/DebugSupport/BlackBoxTest/LoongArch64/DebugSupportBBTestCacheFunction.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/DebugSupport/BlackBoxTest/LoongArch64/DebugSupportBBTestExceptionCallbackFunction.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/DebugSupport/BlackBoxTest/LoongArch64/PlatformIsa.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/Usb2Hc/BlackBoxTest/Usb2HcTest.inf
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/UsbHc/BlackBoxTest/LoongArch64/TimerInterrupt.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/UsbHc/BlackBoxTest/UsbHcTest.inf
uefi-sct/SctPkg/TestInfrastructure/SCT/Framework/ENTS/EasLib/EntsLib.inf
uefi-sct/SctPkg/TestInfrastructure/SCT/Framework/ENTS/EasLib/LoongArch64/EntsLibPlat.h
uefi-sct/SctPkg/TestInfrastructure/SCT/Framework/ENTS/EasLib/LoongArch64/InitPlat.c
uefi-sct/SctPkg/Tools/Source/GenBin/GNUmakefile
uefi-sct/SctPkg/UEFI/IHV_SCT.dsc
uefi-sct/SctPkg/UEFI/Protocol/DebugSupport.h
uefi-sct/SctPkg/UEFI/UEFI_SCT.dsc
uefi-sct/SctPkg/build.sh

LoongArch64 support was merged into edk2 and edk2-platforms, enable it in edk2-test now.

Enable LoongArch64

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/HIIConfigAccess/BlackBoxTest/HIIConfigAccessBBTestFunction.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/HIIConfigRouting/BlackBoxTest/HIIConfigRoutingBBTestFunction.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3759
HIIConfigAccess and HIIConfigRouting Protocol RouteConfig tests assertions store a failure when RouteConfig returns EFI_ACCESS_DENIED. In the UEFI SPEC RouteConfig in both protocols can return EFI_ACCESS_DENIED when the action violates a system policy. The tests now record a pass with warning.
Cc: Sunny Wang <Sunny.Wang@arm.com>
Change-Id: I8591c3d7b0855133141779d3c53a159129400815

uefi-sct/SctPkg: RouteConfig() returns EFI_ACCESS_DENIED passes with warning

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/DevicePathFromText/BlackBoxTest/DevicePathFromTextBBTestCoverage.c

DevicePathFromTextBBTextCoverage.c function CreateDNSDeviceNode has a bug, code:
SctStrToIPv4Addr (&IpStr1, (EFI_IPv4_ADDRESS *)(DNS + sizeof (DNS_DEVICE_PATH)));
DNS is a pointer, which is increased by a structure size and converted to EFI_IPv4_ADDRESS*, which will point to an unknown address. So fix it.
Fixes: 847e0363e846 ("SctPkg: Fix the UefiSct-Wincompatible-pointer-types warnings")
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4712
Cc: Supreeth Venkatesh <Supreeth.Venkatesh@amd.com>
Cc: Heinrich Schuchardt …

SctPkg: Fixed a pinter error in DevicePathFromTextBBTestCoverage.c

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleTextInputEx/BlackBoxTest/SimpleTextInputExBBTestFunction.c
uefi-sct/SctPkg/TestCase/UEFI/IHV/Protocol/SimpleTextInputEx/BlackBoxTest/SimpleTextInputExBBTestFunction.c

REF:  https://bugzilla.tianocore.org/show_bug.cgi?id=2386
Enhance BBTestReadKeyStrokeExFunctionAutoTestCheckpoint1() to handle ReadKeyStrokeEx implementation which returns EFI_NOT_READY but without touching KeyToggleState.
Signed-off-by: Barton Gao <gaojie@byosoft.com.cn>

uefi-sct/SctPkg:Enhance BBTestReadKeyStrokeExFunctionAutoTestCheckpoint1()

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/TCG2/BlackBoxTest/TCG2ProtocolBBTest.h
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/TCG2/BlackBoxTest/TCG2ProtocolBBTestConformance.c
uefi-sct/SctPkg/UEFI/Protocol/TCG2.h

This patch series cleans up some issues found when building edk2-test with a non-GCC compiler:
-TPMT_HA struct had an error due to incorrect use of C flexible array member
-compute struct member offsets using OFFSET_OF, which is not GCC specific
-clean up of #pragma pack in one file
-resolve type conversion warnings
Patches are in github here:
https://github.com/stuyod01/edk2-test/tree/tcg2-cleanup
Version 2
-add SM3 hash type to TPM2.h
-resolve type conversion warnings

Build cleanup

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/AdapterInfo/BlackBoxTest/AdapterInfoBBTestConformance.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/AdapterInfo/BlackBoxTest/AdapterInfoBBTestFunction.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/AdapterInfo/BlackBoxTest/AdapterInfoProtocolBBTest.inf
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/HIIConfigAccess/BlackBoxTest/HIIConfigAccessBBTestConformance.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/HIIConfigAccess/BlackBoxTest/HIIConfigAccessBBTestFunction.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/PxeBaseCode/BlackBoxTest/PxeBaseCodeBBTestConformance.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/PxeBaseCode/BlackBoxTest/PxeBaseCodeBBTestFunction.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleNetwork/BlackBoxTest/SimpleNetworkBBTest.inf
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleNetwork/BlackBoxTest/SimpleNetworkBBTestConformance.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleNetwork/BlackBoxTest/SimpleNetworkBBTestFunction.c

Tests Modified:
AdapterInfoBBTest
HIIConfigAccessBBTest
PxeBaseCodeBBTest
SimpleNetworkBBTest
Uses SctDevicePathStrFromProtocol function from DevicePath.c
UEFI-SCT
Cc: Supreeth Venkatesh <Supreeth.Venkatesh@amd.com>
Signed-off-by: Prachotan Bathi <prachotan.bathi@arm.com>

EDK2-Test BUG4244 V2 - Print PCIe device path for SCT failures

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleNetwork/BlackBoxTest/SimpleNetworkBBTestFunction.c

The current time delay in the SCT GetStatus_Func test is 5 milliseconds, which caused false positives with some platforms This time delay is increased to 500 miliseconds with reference to similar values in https://github.com/tianocore/edk2/blob/master/NetworkPkg/Include/Library/NetLib.h#L265
Signed-off-by: G Edhaya Chandran <edhaya.chandran@arm.com>
Co-authored-by: Sunny Wang <sunny.wang@arm.com>
Reviewed-by: Stuart Yoder <stuart.yoder@arm.com>

uefi-sct: Increase the waiting time in the SCT GetStatus_Func test

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/HIIConfigAccess/BlackBoxTest/HIIConfigAccessBBTestFunction.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4847
EFI_ACCESS_DENIED (The action violated a system policy) is an acceptable status for ExtractConfig in UEFI specification.
SCT now marks the test case as a warning instead of failure, when EFI_ACCESS_DENIED is returned.
Reviewed-by: G Edhaya Chandran <Edhaya.Chandran@arm.com>
Reviewed-by: Sunny Wang <Sunny.Wang@arm.com>

uefi-sct/SctPkg: ExtractConfig allows EFI_ACCESS_DENIED with a warning

---

uefi-sct/SctPkg/UEFI/IHV_SCT.dsc
uefi-sct/SctPkg/UEFI/UEFI_SCT.dsc

edk2 PR tianocore/edk2#6048 moves
ArmCompilerIntrinsicsLib to MdePkg and into MdeLibs.dsc.inc.
This patch drops all of the references to the ArmPkg location as these *_SCT.dsc are now getting it from MdeLibs.dsc.inc. This is done in one shot as it is a breaking change and has no functional impact.

SctPkg: Drop ArmCompilerIntrinsicsLib

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/DevicePath/BlackBoxTest/DevicePathBBTestFunction.c

The DevicePathBBTest wrongly flags the failure for a valid VLAN device path node. For e.g. value 4040
The range check for vlanId is corrected to fix this issue.
https://bugzilla.tianocore.org/show_bug.cgi?id=4710
Signed-off-by: G Edhaya Chandran <edhaya.chandran@arm.com>
Reviewed-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>

edk2-test: uefi-sct: Correct the vlanId check in DevicePath Test

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/TCG2/BlackBoxTest/TCG2ProtocolBBTestConformance.c

Previously, the test only validated SHA-256 in EFI_TCG2_BOOT_SERVICE_CAPABILITY.HashAlgorithmBitmap, This update checks all supported SHA256-or-stronger algorithms.
Signed-off-by: Amrathesh <amrathesh@arm.com>
Reviewed-by: Stuart Yoder <stuart.yoder@arm.com>

uefi-sct/SctPkg: TCG2 Protocol: Expand BSCap.HashAlgorithmBitmap check

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/AdapterInfo/BlackBoxTest/AdapterInfoBBTestConformance.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/AdapterInfo/BlackBoxTest/AdapterInfoBBTestFunction.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/AdapterInfo/BlackBoxTest/AdapterInfoBBTestMain.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/AdapterInfo/BlackBoxTest/AdapterInfoBBTestMain.h

Fixes: df9a877
AdapterInfoBBTest halts with a synchronous exception. Including "SctLib.h" fixes the issue.
Cc: Supreeth Venkatesh <Supreeth.Venkatesh@amd.com>

Edk2-Test: Fix:AdapterInfoBBTest

---

uefi-sct/SctPkg/TestCase/UEFI/IHV/Protocol/AdapterInfo/BlackBoxTest/Guid.c

The EFI_ADAPTER_INFORMATION_PROTOCOL Test 5.5.11.1.2 always FAILS with the AIP Support Type gEfiAdapterInfoNetworkBootGuid.
In the Guid C file, gEfiAdapterInfoUndiIPv6SupportGuid is assigned to an incorrect Guid.
Correct the gEfiAdapterInfoUndiIPv6SupportGuid assignment to **EFI_ADAPTER_INFO_UNDI_IPV6_SUPPORT_GUID** to fix this bug.
refer Bug#240: https://github.com/tianocore/edk2-test/issues/240

edk2-test: uefi-sct: Correct the AIP GUID gEfiAdapterInfoUndiIPv6SupportGuid definition.

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/TCG2/BlackBoxTest/TCG2ProtocolBBTest.h
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/TCG2/BlackBoxTest/TCG2ProtocolBBTestConformance.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/RuntimeServices/TCGMemoryOverwriteRequest/BlackBoxTest/TCGMemoryOverwriteRequestBBTestFunction.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/RuntimeServices/TCGMemoryOverwriteRequest/BlackBoxTest/TCGMemoryOverwriteRequestBBTestMain.h

The `SctPkg` does not build with GCC 14, with the following error:
```
/buildroot/cyan/edk2-test/uefi-sct/SctPkg/TestCase/UEFI/EFI/RuntimeServices/TCGMemoryOverwriteRequest/BlackBoxTest/TCGMemoryOverwriteRequestBBTestMain.c:54:5: error: initialization of ‘EFI_STATUS (__attribute__((ms_abi)) *)(EFI_BB_TEST_PROTOCOL *, void *, EFI_TEST_LEVEL,  void *)’ {aka ‘long long unsigned int (__attribute__((ms_abi)) *)(struct _EFI_BB_TEST_PROTOCOL *, void *, unsigned int,  void *)’} from incompatible pointer type ‘EFI_STATUS (*)(EFI_BB_TEST_PROTOCOL *, void *, EFI_TEST_LEVEL,  void *)’ {aka ‘long long unsigned int (*)(struct _EFI_BB_TEST_PROTOCOL *, void *, unsigned int,  void *)’} [-Wincompatible-pointer-types]
54 |     BBTestTCGMemoryOverwriteRequestFunctionTest
| …
```

TestCase: Add missing EFIAPI specifier in test entry points to fix FTBFS w/ GCC 14

---

.github/scripts/GitHub.py

Since case of a GitHub user name may by specified differently in the `Maintainers.txt` file versus what is actually returned by the GitHub API (actual case), convert both to lowercase for comparison.
Other GitHub user name inputs are directly from APIs and maintain consistent casing.
From edk2 commit:
https://github.com/tianocore/edk2/commit/607c58ef010c9952263f5e5e2553ece4dd2067bc
Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com

.github: Compare collaborator GitHub ID's in single case

---

uefi-sct/SctPkg/Library/SctLib/Hob.c

Use SctCopyMem instead of EfiCommonLibCopyMem
Signed-off-by: Anbazhagan Baraneedharan <anbazhagan@hp.com>

uefi-sct/SctPkg: Fix copy mem build error

---

uefi-sct/SctPkg/build.sh

fixes: https://github.com/tianocore/edk2-test/issues/244

uefi-sct/SctPkg: Fixes "Unsupported target architecture X64 !"

---

uefi-sct/Doc/TestCaseSpec/02_EFI_Compliance_Test.md

The test scenario update for EFI_RT_PROPERTIES_TABLE as introduced in the UEFI v2.8 version.
See https://github.com/tianocore/edk2-test/issues/256 for more details. 
Corresponding code PR: https://github.com/tianocore/edk2-test/pull/114

[New test coverage] Test Scenario for EFI_RT_PROPERTIES_TABLE

---

uefi-sct/SctPkg/build.sh

This adds support in build.sh to enable CLANGDWARF based SCT build.
fixes: https://github.com/tianocore/edk2-test/issues/261

uefi-sct/SctPkg: Enable CLANGDWARF processing in build script

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/RuntimeServices/TimeServices/BlackBoxTest/TimeServicesBBTestMain.c

Updating the TimeFieldsValid() function to validate the Year field against the full range specified in the UEFI spec (1900–9999) to ensure compliance
Fixes #263 
This patch resolves the issue by correcting the logic in TimeFieldsValid()

uefi-sct/TimeServices: Updating the TimeFieldsValid() function

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/ImageServices/BlackBoxTest/Dependency/ValidHiiImage1/ValidHiiImage1.inf

REF: https://github.com/tianocore/edk2-test/issues/271
Remove the [Guids] entry for gTestGenericFailureGuid in ValidHiiImage1.inf, as this GUID is already defined and implemented in EfiTestLib. Leaving this entry causes multiple definition errors when linking with GCC.
Cc: Sunny Wang <sunny.wang@arm.com>
Cc: Simon Yang <simon1.yang@intel.com>

SctPkg: Remove duplicate gTestGenericFailureGuid definition in ValidHiiImage

---

uefi-sct/SctPkg/Config/Data/Category.ini
uefi-sct/SctPkg/TestCase/UEFI/EFI/Generic/EfiCompliant/BlackBoxTest/EfiCompliantBBTestPlatform_uefi.c

REF: https://github.com/tianocore/edk2-test/issues/280
edk2 master removes all supported code for UGAIO, this causes build failures due to absence of ugaio.h.
This patch removes the dependency on UGAIO and fixes the build issue.
Cc: Sunny Wang <sunny.wang@arm.com>
Cc: Ann Cheng <ann.cheng@arm.com>
Cc: Richard Lyu <richard.lyu@suse.com>

uefi-sct/SctPkg: Fixed build issue due to no UGAIO.

---

uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/DevicePathToText/BlackBoxTest/DevicePathToTextBBTestMain.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleTextIn/BlackBoxTest/SimpleTextInBBTestConformance.c
uefi-sct/SctPkg/TestCase/UEFI/EFI/Protocol/SimpleTextIn/BlackBoxTest/SimpleTextInBBTestStress.c
uefi-sct/SctPkg/TestInfrastructure/SCT/Drivers/TestProfile/TestProfile.c
uefi-sct/SctPkg/TestInfrastructure/SCT/Framework/ENTS/MonitorServices/ManagedNetworkMonitor/ManagedNetworkMonitor.c

Fixed high impact corruption errors found using Coverity static code analysis

uefi-sct/SctPkg: Coverity corruptions fixes

---

uefi-sct/SctPkg/UEFI/Protocol/PxeBaseCode.h

Updated DEFAULT_TTL value to match the updated edk2 value.
https://github.com/tianocore/edk2/commit/9144bb940a816130ccd5cd6cd62d88bfcfd3de20
Default IP TTL (Time to Live) has been updated in UEFI 2.10 A
Specification. To comply with IANA recommendations.
REF: https://www.iana.org/assignments/ip-parameters/ip-parameters.xhtml#ip-parameters-2

uefi-sct/SctPkg: Updated DEFAULT_TTL Value
